apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  labels:
    app: {{ .Values.appName }}
    env: {{ .Values.environment }}
data:
  APP_ENV: {{ .Values.config.APP_ENV | quote }}
  APP_NAME: {{ .Values.config.APP_NAME | quote }}