apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
  labels:
    app: {{ .Values.appName }}
    env: {{ .Values.environment }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secretData.DB_PASSWORD | quote }}